"""update tables13

Revision ID: 0280474fa526
Revises: e14371b653dd
Create Date: 2024-07-04 14:00:18.942431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0280474fa526'
down_revision: Union[str, None] = 'e14371b653dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'complete')
    # ### end Alembic commands ###
