"""update tables24

Revision ID: 2ab3d8008efc
Revises: 64bc0ae75d54
Create Date: 2024-07-04 16:09:11.331644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab3d8008efc'
down_revision: Union[str, None] = '64bc0ae75d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('type', sa.VARCHAR(length=11), nullable=False))
    # ### end Alembic commands ###
