"""update tables13

Revision ID: 41aa441f4d7e
Revises: 0280474fa526
Create Date: 2024-07-04 14:04:36.618973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41aa441f4d7e'
down_revision: Union[str, None] = '0280474fa526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('title2', sa.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
