"""update tables7

Revision ID: 67f498ad40c7
Revises: 57b0e324efb5
Create Date: 2024-07-04 13:45:05.476645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f498ad40c7'
down_revision: Union[str, None] = '57b0e324efb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('complete2', sa.Boolean(), nullable=True))
    op.drop_column('todos', 'title2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('title2', sa.VARCHAR(length=200), nullable=False))
    op.drop_column('todos', 'complete2')
    # ### end Alembic commands ###
