"""update tables18

Revision ID: a1173c016869
Revises: 6ce97df0c432
Create Date: 2024-07-04 14:45:38.739309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1173c016869'
down_revision: Union[str, None] = '6ce97df0c432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('todos', sa.Column('complete', sa.Boolean(), nullable=True))
    op.alter_column('todos', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('todos', 'complete')
    # ### end Alembic commands ###
