"""update tables8

Revision ID: be9bd768ddfc
Revises: 67f498ad40c7
Create Date: 2024-07-04 13:49:05.822403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9bd768ddfc'
down_revision: Union[str, None] = '67f498ad40c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('complete', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'complete')
    # ### end Alembic commands ###
