"""update tables22

Revision ID: d8898fe7e29b
Revises: 360b2f030bc6
Create Date: 2024-07-04 15:24:48.099489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8898fe7e29b'
down_revision: Union[str, None] = '360b2f030bc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('title', sa.String(length=200), nullable=False))
    op.add_column('todos', sa.Column('type', sa.Enum('in_progress', 'not_start', 'pause', name='typetodo'), nullable=True))
    op.alter_column('todos', 'complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('todos', 'type')
    op.drop_column('todos', 'title')
    # ### end Alembic commands ###
