"""Add col username2

Revision ID: 9bd2812cc27f
Revises: dc7161628f6c
Create Date: 2024-07-11 19:55:57.587685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bd2812cc27f'
down_revision: Union[str, None] = 'dc7161628f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username2', sa.String(100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username2')
    # ### end Alembic commands ###
