"""Del username2 

Revision ID: d93d82460f7e
Revises: fd747f0a06ae
Create Date: 2024-07-11 19:59:25.091523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd93d82460f7e'
down_revision: Union[str, None] = 'fd747f0a06ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username2', sa.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
