"""Add col username2 ? []

Revision ID: fd747f0a06ae
Revises: 9bd2812cc27f
Create Date: 2024-07-11 19:57:41.697159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd747f0a06ae'
down_revision: Union[str, None] = '9bd2812cc27f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
